config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get "guess_admin", to: "instas#guest_admin"
  get "guess", to: "instas#guest"
  devise_for :users
  get '/users_profil', to:'users#profil', as: 'profil'
  root 'instas#index'
  resources :publications do
    resources :comments
  end
  resources :likes, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
  get '/publications_publication', to:'publications#publication', as: 'allpub'
  get '/publications_publi', to:'publications#publi', as: 'userpub'
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :publication
  validates :content, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :publication
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :publication
end

app/models/publication.rb
class Publication < ApplicationRecord
  belongs_to :user
  validates :content, presence: true
  mount_uploader :image, ImageUploader
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :like_users, through: :likes, source: :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  mount_uploader :image, ImageUploader
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :publications, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :favorites, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    protected
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:account_update, keys: [:name, :image])
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name,  :image])
    end
    
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_publication, only: [:create, :edit, :update]
  def create
    @comments = Comment.where(publication_id: @publication)
    @comment = @publication.comments.build(comment_params)
    @comment.user_id = current_user.id
    respond_to do |format|
      if @comment.save
        format.html { redirect_to publication_path(@publication) }
        format.js { render :index }
      else
        format.html { redirect_to publication_path(@publication), notice: "Couldn't post..." }
        format.js { redirect_to publication_path(@publication), notice: "Couldn't post..." }
      end
    end
  end
  def edit
    @comment = @publication.comments.find(params[:id])
    respond_to do |format|
      flash.now[:notice] = 'Editing comment'
      format.js { render :edit }
    end
  end
  def update
    @comment = @publication.comments.find(params[:id])
    respond_to do |format|
      if @comment.update(comment_params)
        format.js { render :index }
      else
        format.js { render :edit_error }
      end
    end
  end
  def destroy
    @comment = Comment.find(params[:id])
    @publication.order("created_at DESC")
    @comment.destroy
    respond_to do |format|
      #flash.now[:notice] = 'Comment deleted'
      format.html { redirect_to publication_path(@publication)}
      format.js { render :index }
    end
  end


  private
    def comment_params
      params.require(:comment).permit(:user_id, :publication_id, :content)
    end
    def set_publication
      @publication = Publication.find(params[:publication_id])
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
    def create
        favorite = current_user.favorites.create(publication_id: params[:publication_id])
        redirect_to publication_path(favorite.publication), notice: "Publication ajoutée aux favories"
      end
      def destroy
        favorite = current_user.favorites.find_by(id: params[:id]).destroy
        redirect_to publication_path(favorite.publication), notice: "Publication supprimée des favories"
      end
end

app/controllers/instas_controller.rb
class InstasController < ApplicationController
    def index
        
    end

    def guest
        @user = User.find_by(email: "guess@instafriends.com")
        unless @user
            @user = User.create!(email: "guess@instafriends.com", password: "password", is_admin: false)
        end

        sign_in @user
        redirect_to root_path, notice: "Connecter avec succès!"
    end

    def guest_admin
        @user = User.find_by(email: "admin_guess@instafriends.com")
        unless @user
            @user = User.create!(email: "admin_guess@instafriends.com", password: "password", is_admin: true)
        end
        
        sign_in @user
        redirect_to rails_admin_path if current_user.is_admin != false
        redirect_to root_path, notice: 'Accès reservé aux administrateurs' if current_user.is_admin != true
    end
    
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        like = current_user.likes.create(publication_id: params[:publication_id])
        redirect_to publication_path(like.publication), notice: "J'aime"
      end
      def destroy
        like = current_user.likes.find_by(id: params[:id]).destroy
        redirect_to publication_path(like.publication), notice: "J'aime plus"
      end
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_publication, only: %i[ show edit update destroy ]
  
    def publication
      @publications = Publication.all
      @users = User.all
    end

    def publi
        @publicat = current_user.publications.all
        @users = User.all
    end
  
    def show 
        @comments = @publication.comments
        @comment = @publication.comments.build
        @like = current_user.likes.find_by(publication_id: @publication.id)
        @favorite = current_user.favorites.find_by(publication_id: @publication.id)
    end
  
    def new
      @publication = Publication.new
    end
  
    def edit
    end
  
    def create
      @publication = current_user.publications.build(publication_params)
      #@publication.user_id = current_user.id
      respond_to do |format|
        if @publication.save
          #PublicationMailer.published_mail(@publication).deliver
          format.html { redirect_to @publication, notice: "Publication crée avec succès." }
          format.json { render :show, status: :created, location: @publication }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @publication.errors, status: :unprocessable_entity }
        end
      end
    end

    def update
      respond_to do |format|
        if @publication.update(publication_params)
          format.html { redirect_to @publication, notice: "Publication mise à jour." }
          format.json { render :show, status: :ok, location: @publication }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @publication.errors, status: :unprocessable_entity }
        end
      end
    end
  
    def destroy
      @publication.destroy
      respond_to do |format|
        format.html { redirect_to allpub_path, notice: "Publication supprimé." }
        format.json { head :no_content }
      end
    end
  
    private
    def set_publication
      @publication = Publication.find(params[:id])
    end
  
    def publication_params
      params.require(:publication).permit(:image, :image_cache, :content)
    end
end
  

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
    def profil
        @publicat = current_user.publications.all
        @users = User.all
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/publications_helper.rb
module PublicationsHelper
    
  end

app/views/comments/_edit.html.erb
<%= form_with(model: [@publication, @comment], remote: true) do |form| %>
    <% if comment.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
        <ul>
        <% comment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="field">
      <%= form.text_area :content, id: "comment_content_#{publication.id}" %>
      <%= form.label :content %>
    </div>
    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>

app/views/comments/_form.html.erb
<%= form_with(model: [@publication, @comment || @publication.comments.build], remote: true) do |form| %>
    <% if comment.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
        <ul>
        <% comment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="field">
      <%= form.label :content %>
      <%= form.text_area :content, placeholder: "Ecrivez votre Commentaire." %>
    </div>
    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>

app/views/comments/_index.html.erb
<% comments.each do |comment| %>
  <div class="feed-element">
    <div class="media-body" style="font-size:14px;">
      <% if comment.id.present? %>  
        <div class="well" style="font-size:14px;">
          <div class="comment-content" id ="this_comment_<%= comment.id %>">
            <span class="pull-right text-navy"><%= time_ago_in_words(comment.created_at) %> ago</span>
            <strong><%= comment.user.name %></strong> commented this publication.
              <br>
            <strong> Commentaire : </strong><%= comment.content %>
          </div>
          
        </div> <br>
      <% end %>
    </div>
  </div>
<% end %>

app/views/comments/destroy.js.erb
$('#comment_<%= @comment.id %>').remove();

app/views/comments/edit.js.erb
$("#this_comment_<%= @comment.id %>").replaceWith("<%= j render 'comments/edit', publication: @publication, comment: @comment %>");
$("#notice").html("<%= j flash[:notice] %>");

app/views/comments/index.js.erb
$("#comments_area").html("<%= j(render 'comments/index', { comments: @comment.publication.comments, publication: @comment.publication }) %>");
$("textarea").val('');
$("#notice").html("<%= j flash[:notice] %>");

app/views/frontend/_footer.html.erb
<footer class="bg-light text-center text-lg-start fixed-bottom">
    <div class="text-right mb-2">
    <% if user_signed_in? %>
        <%= link_to "Nouvelle publications", new_publication_path, class: "btn btn-success" %> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      <% else %>
      
      <% end %>
      </div>
    <!-- Copyright -->
    <div class="text-center p-3" style="background: linear-gradient(to right, #feda75, #fa7e1e, #d62976, #962fbf, #4f5bd5);">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      © 2021 Copyright:
      <a class="text-dark" href="/">Insta-Friends</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    </div>
    <!-- Copyright -->
  </footer>

app/views/frontend/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-blue  mb-3" style="background: linear-gradient(to right, #feda75, #fa7e1e, #d62976, #962fbf, #4f5bd5);">
    <div class="container">
        <a class="navbar-brand" href="/">Insta-Friends</a>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                
                <% if user_signed_in? %>
                    <%= link_to "Accueil", root_path, class: "btn btn-white" %> &nbsp;&nbsp;
                    <%= link_to "Tooutes les publications", allpub_path, class: "btn btn-white" %> &nbsp;&nbsp;
                    <%= link_to "Mes Publications", userpub_path, class: "btn btn-white" %> &nbsp;&nbsp;
                    <%= link_to "Profile", profil_path, class: "btn btn-white" %> &nbsp;&nbsp;
                    <%= link_to "Admin", guess_admin_path, class: "btn btn-outline-warning" %> &nbsp;&nbsp;
                    <%= button_to "Deconnexion", destroy_user_session_path, method: :delete, class: "btn btn-danger "%>
                <% else %> 
                    <%= link_to "Connexion", new_user_session_path, class: "btn btn-white" %> &nbsp;&nbsp;&nbsp;
                    <%= link_to "Inscription", new_user_registration_path, class: "btn btn-success" %> &nbsp;&nbsp;&nbsp;
                    <%= link_to "Invité", guess_path, class: "btn btn-warning" %> &nbsp;&nbsp;&nbsp;
                    <%= link_to "Admin invité", guess_admin_path, class: "btn btn-outline-warning" %> &nbsp;&nbsp;&nbsp;
                <% end %>                               
            </ul>
        </div>
    </div>
</nav>

app/views/layouts/application.html copy.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Insta-Friends</title>
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>

        <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="css/styles.css" rel="stylesheet" />
        <meta name="viewport" content="width=device-width,initial-scale=1">

        <link
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css"
          rel="stylesheet"
        />
        <!-- Google Fonts -->
        <link
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
          rel="stylesheet"
        />
        <!-- MDB -->
        <link
          href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.css"
          rel="stylesheet"
        />
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">

        
    <!-- Our Custom CSS -->
    <link rel="stylesheet" href="css/style.css">
    <!-- Scrollbar Custom CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.min.css">

    <!-- Font Awesome JS -->
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js" integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ" crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js" integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY" crossorigin="anonymous"></script>
    </head>
  <body style="background: #fafafa !important;">

  <%= render "frontend/header" %>
    
    <%= yield  %>
    
    <%= render "frontend/footer" %>

    <!-- MDB -->
<script
  type="text/javascript"
  src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.js"
></script>
<!-- Bootstrap core JS-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"></script>
<!-- Core theme JS-->
<script src="js/scripts.js"></script>
<!-- Popper.JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <!-- Bootstrap JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
    <!-- jQuery Custom Scroller CDN -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.concat.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $("#sidebar").mCustomScrollbar({
                theme: "minimal"
            });

            $('#sidebarCollapse').on('click', function () {
                $('#sidebar, #content').toggleClass('active');
                $('.collapse.in').toggleClass('in');
                $('a[aria-expanded=true]').attr('aria-expanded', 'false');
            });
        });
    </script>
  </body>
</html>

app/views/publications/_form.html.erb
<div class="container mb-2">
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8 ">
            <div class="card">
                <div class="card-header text-center mt-5">
                    
                </div>
                <div class="card-body text-center">
                     
                    <%= form_with(model: @publication, local: true ) do |form| %>
                    <% if publication.errors.any? %>
                      <div id="error_explanation">
                        <h2><%= pluralize(publication.errors.count, "error") %> prohibited this publication from being saved:</h2>

                        <ul>
                          <% publication.errors.full_messages.each do |message| %>
                            <li><%= message %></li>
                          <% end %>
                        </ul>
                      </div>
                    <% end %>

                    <div class="field">
                      <%= form.file_field :image %>
                      <%= form.hidden_field :image_cache %>
                    </div><br>

                    <div class="field">
                      <%= form.label :content %><br>
                      <%= form.text_area :content, placeholder: "Commentez votre image." %>
                    </div><br>

                    <div class="actions">
                      <%= form.submit %>
                    </div>
                    <% end %>
                 </div>
                 <div class="card-footer text-center mb-5">
                   <%= link_to 'Back', publications_path %>
                 </div>
             </div>
         </div>
         <div class="col-md-2"></div>
    </div>
</div>

app/views/publications/edit.html.erb
<div class="text-center">
	<h1>Editing Publication</h1>
</div>

<%= render 'form', publication: @publication %>

app/views/publications/new.html.erb
<div class="text-center">
	<h1>Nouvelle Publication</h1>
</div>

<%= render 'form', publication: @publication %>

app/views/publications/publi.html.erb
<p id="notice"><%= notice %></p>
<div class="text-center">
  <h2>Mes Publications</2>
</div>

<div style="margin-top: 50px;">
<% @publicat.each do |publication| %>
  
<div class="row">
  <div class="col-md-2">
    
  </div>

  <div class="col-md-8 mb-3">
      <div class="card mb-3">

    <p class="card-text mt-3">
        &nbsp;&nbsp;&nbsp;
      <i class="fas fa-user"></i>
        &nbsp;
        <% @users.each do |usere| %>
          <% if publication.user_id == usere.id %>
              <%= usere.name %>
          <% end %>
        <% end %>
        </p>
        <div class="card-body">
          <img
            src="<%= publication.image %>"
            class="card-img-top"
            alt="..."
          />
        </div>
        <div class="text-center">
          <%= publication.content %><br>
        </div><br>
        <div class="card-footer"></div>
          <div class="flex text-center">
            <% if publication.user_id == current_user.id %>
              <%= link_to 'Voir', publication %>||
              <%= link_to 'Modifier', edit_publication_path(publication) %> ||
              <%= button_to 'Supprimer', publication, method: :delete, data: { confirm: 'Are you sure?' } %>
            <% else %>
              <%= link_to 'Voir', publication %>||
            <% end %>
          </div>
    <div class="card-body">
      
      <p class="card-text text-center" style="margin-top: -15px;">
       
      <div class="row">
        <div class="col-6 ">
          <p class="card-text">
            <small class="text-muted">Publié le <%= publication.created_at %></small>
          </p>
          <br>
        </div>
        
      </div>

    </div> 
</div>

</div>

<% end %>

</div>

app/views/publications/publication.html.erb
<p id="notice"><%= notice %></p>
<div class="text-center">
  <h2>Toutes Publications</h2>
</div>

<div style="margin-top: 50px;">

<% @publications.each do |publication| %>
  
<div class="row">
  <div class="col-md-2">
    
  </div>

  <div class="col-md-8 mb-3">
      <div class="card mb-3">

    <p class="card-text mt-3">
        &nbsp;&nbsp;&nbsp;
      <i class="fas fa-user"></i>
        &nbsp;
        <% @users.each do |usere| %>
          <% if publication.user_id == usere.id %>
              <%= usere.name %>
          <% end %>
        <% end %>
        </p>
        <div class="card-body">
          <img
            src="<%= publication.image %>"
            class="card-img-top"
            alt="..."
          />
        </div>
        <div class="text-center">
          <%= publication.content %><br>
        </div><br>
        <div class="card-footer"></div>
          <div class="flex text-center">
            <% if publication.user_id == current_user.id %>
              <%= link_to 'Voir', publication %>||
              <%= link_to 'Modifier', edit_publication_path(publication) %> ||
              <%= button_to 'Supprimer', publication, method: :delete, data: { confirm: 'Are you sure?' } %>
            <% else %>
              <%= link_to 'Voir', publication %>
            <% end %>
          </div>
    <div class="card-body">
      
      <p class="card-text text-center" style="margin-top: -15px;">
       
      <div class="row">
        <div class="col-6 ">
          <p class="card-text">
            <small class="text-muted">Publié le <%= publication.created_at %></small>
          </p>
          <br>
        </div>
        
      </div>

    </div> 
</div>

</div>

<% end %>

</div>

app/views/publications/show.html.erb
<div class="text-center">
  <h2>Publication</2>
</div>
<div class="container mb-8">

    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <div class="card">
                <div class="card-header text-right">
                
                </div>
                <div class="card-body text-center">
                     
                     <p id="notice"><%= notice %></p>
                    <p>
                      <img
                        src="<%= @publication.image %>"
                        class="img-fluid"
                        alt=""
                        style="margin-top: 30px;"
                      />
                    </p>
                    <p>
                      <%= @publication.content %>
                    </p>
                    
                 </div>
                 <div class="card-footer center d-flex">
                    <% if @like.present? %>
                      <%= button_to 'Unlike', like_path(id: @like.id), method: :delete, class: 'btn btn-danger' %>&nbsp;&nbsp;&nbsp;<i class="fas fa-heart fa-2x"></i>&nbsp;<p style="font-size:25px; color:red"><%= @publication.likes.count %></p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;||&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <% else %>
                      <%= button_to 'Like', likes_path(publication_id: @publication.id), method: :post, class: 'btn btn-primary' %>&nbsp;&nbsp;&nbsp;<i class="fas fa-heart fa-2x"></i>&nbsp;<p style="font-size:25px; color:red"><%= @publication.likes.count %></p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;||&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <% end %>
                    <% unless @publication.user_id == current_user.id %>
                      <% if @favorite.present? %>
                        <%= button_to 'Supprimer des favories', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-outline-danger' %> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;||&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                      <% else %>
                        <%= button_to 'Mettre en Favorie', favorites_path(publication_id: @publication.id), method: :post, class: 'btn btn-outline-primary' %> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;||&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                      <% end %>
                    <% end %>
                    <% if current_user.id == @publication.user_id %>
                      <%= button_to 'Modifier', edit_publication_path, method: :get  %> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;||&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                      <%= button_to 'Supprimer', publication_path(@publication.id), method: :delete %>
                    <% end %>  
                 </div>
                 <div class="card-footer text-center">
                 <div id="comments_area">
                 <%= render partial: 'comments/index', locals: { comments: @comments, publication: @publication, user: @user } %>
                  </div>
                  <%= render partial: 'comments/form', locals: { comment: @comment, publication: @publication } %>
                  </div>
             </div>
         </div>
         <div class="col-md-1"></div>
    </div>
</div>